config/routes.rb
# require 'resque/server'
Rails.application.routes.draw do
  devise_for :users, :path => ""


  # Of course, you need to substitute your application name here, a block
  # like this probably already exists.
  # mount Resque::Server.new, at: "/resque"
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  # Api for grape
  mount API => '/'

  resources :users, :path => "", only: :index do
  end

  resources :presses do
  	member do 
      put :toggle
      get :inventory
      get :metrics
  	end
  end

  resources :rannars do
    collection do
      get "delivery"
    end
    member do
    end
  end

  resources :orders do
    member do
      get :download
      post :status
    end
  end

  resources :countries
  resources :vouchers do
    collection do
      get   :print
      post  :get_pdf
    end
  end
  resources :customers
  
	resources :transactions do
		collection do
			get :export_csv
		end
	end
	resources :reports
	resources :settings do
		collection do
			put :password
		end
	end

  resources :dashboards
  resources :charges
  resources :services do
    member do
      namespace :services do
        resources :papers
      end
    end
  end

  root "dashboards#index"
end

app/models/service.rb
class Service < ApplicationRecord
	belongs_to :press
	has_many 	 :papers, dependent: :destroy

	validates :name, presence: true, uniqueness: { scope: :press_id }
end

app/controllers/services/papers_controller.rb
class Services::PapersController < ServicesController
  before_action :find_service

  def index
  end

  def new
    @paper = @service.papers.new
  end

  def create
    @paper = @service.papers.new(paper_params)
    @paper.price *= 100    
    if @paper.save
			flash[:notice] = "Paper successfully saved"
			redirect_to service_url(@service)
		else
			flash[:alert] = "Error saving paper. Please try again. #{@paper.errors.as_json}"
			render "new"
		end
  end

  def edit
    find_paper
  end

  def update
    find_paper
    paper_params[:price] = paper_params[:price] * 1000

    if @paper.update_attributes(paper_params)
      @paper.price *= 100
      @paper.save
			flash[:notice] = "Paper has successfully been updated."
			redirect_to service_url(@service)
		else
			flash[:alert] = "An error was encountered while updating paper. Please try again later"
			render "edit"
		end
  end

  # Removes a paper
  def destroy
    find_paper
    flash[:notice] = "Paper successfully removed"
    @paper.destroy
    redirect_to service_url(@service)
  end

  private 
  def find_service
    @service = current_user.press.services.find(params[:id])

    unless @service.present?
      redirect_to services_url
      return ;
    end
  end

  def find_paper
    @paper = @service.papers.find(params[:pid])
    unless @paper.present?
      redirect_to service_url(@service)
      return ;
    end
  end

  def paper_params
		params.require(:paper).permit(:size,:ptype,:unit,:price,:currency,:color)
	end
end

app/controllers/services_controller.rb
class ServicesController < UsersController
  before_action :build_query
  # Service index page
  # Display list of available services
  def index
    @services = Service.where(@query)
      .page(params[:page] || 1)
      .order("created_at DESC")
  end

  # shows form for creating new service
  def new
    if current_user.has_press?
      @service = current_user.press.services.new
    else
      @service = Service.new
    end
  end

  # Saves a new service
  def create
    @service = current_user.press.services.new(service_params)
		if @service.save
			flash[:notice] = "Service successfully saved"
			redirect_to services_url
		else
			flash[:alert] = "Error saving service. Please try again. #{@service.errors.as_json}"
			render "new"
		end
  end

  # Shows a particular service
  def show
    find_service
  end

  # Provides a form for editing service
  def edit
    find_service
  end

  # Updates a service
  def update
    find_service

		if @service.update_attributes(service_params)
			flash[:notice] = "Service has successfully been updated."
			redirect_to services_url
		else
			flash[:alert] = "An error was encountered while updating service. Please try again later"
			render "edit"
		end
  end

  def destroy
    find_service
    @service.destroy
    flash[:notice] = "Service successfully removed."
    redirect_to services_url
  end

  private

  def build_query
    @query = []

    # If the user belongs to a press
    # scope the displayed inormation
    if current_user.has_press?
      @query << "press_id = '#{current_user.press.id}'"
    end

    if params[:q].present?
      @query << "name LIKE '\%#{params[:q]}\%'"
    end

    # Add the query strings together
    @query = @query.join(" AND ")
  end

  def service_params
		params.require(:service).permit(:name, :description)
  end
  
  def find_service
    @service = current_user.press.services.find(params[:id])

		unless @service.present?
			flash[:alert] = "Error.. Service not found."
			redirect_to services_url
			return ;
		end
  end
end

app/helpers/services/papers_helper.rb
module Services::PapersHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-6">
			<br>
			<h2><%= action == "create" ? "Add" : "Edit" %> Service</h2>
			<br>
				<%= form_for @service, url: {action: action}, html: {class: "form"} do |f| %>
				  <div class="form-group">
					  <%= f.label :name %>
					  <%= f.text_field :name, class: "form-control" %>
				  </div>
				  <div class="form-group">
					  <%= f.label :description %>
					  <%= f.text_area :description, class: "form-control" %>
				  </div>
				  <div class="form-group">
				  	<%= f.submit action.titleize, class: "btn-success form-control" %>
				  </div>
				<% end %>
		</div>
	</div>
</div>

app/views/services/edit.html.erb
<%= render partial: 'services/form', locals: {action: "update"} %>

app/views/services/index.html.erb
<div class="container-fluid" style="padding-top: 1.5%">
	<div class="row">
		<div class="col-md-12">
			<h5>Services &nbsp; <a href="<%= new_service_url %>" class="btn btn-success btn-sm">+ Add</a></h5>
			<%= render partial: "shared/search", locals: {search_by: "Search Service"} %>
			<% if @services.present? %>
			<br>
			<table class="table table-stripped">
				<tr>
					<th></th>
					<th>Name</th>
					<th width="60%">Description</th>
					<th>Options</th>
				</tr>
				<% 	cnt = 0
						@services.each do |service| %>
					<tr>
						<td><%= cnt+= 1 %></td>
            <td><%= service.name %></td>
            <td><%= service.description %></td>
            <td>
              <a href="<%= service_url(service) %>" class="btn btn-success btn-sm"><%= fa_icon "eye" %> View</a>
              <a href="<%= edit_service_url(service) %>" class="btn btn-primary btn-sm"> <%= fa_icon "pencil" %> Edit</a>
							<%= link_to('Delete', service_url(service), method: :delete, class: "btn btn-danger btn-sm") %>
            </td>
					</tr>
				<% end %>
			</table>
			<%= paginate @services %>
			<% else %>
				<center><h5>No Service Registered</h5></center>
			<% end %>
		</div>
	</div>
</div>

app/views/services/new.html.erb
<%= render partial: 'services/form', locals: {action: "create"} %>

app/views/services/show.html.erb
<br>
<a href="<%= services_url %>" class="btn btn-danger btn-sm"> < Back </a>
<br><br>
<h5>Service Information</h5>
<table class="table table-hover">
    <tr>
        <td width="15%"><b>Name</b></td>
        <td><%= @service.name %></td>
    </tr>
    <tr>
        <td><b>Description</b></td>
        <td><%= @service.description %>
    </tr>
</table>

<br>
<h5>Paper Types &nbsp; <a href="<%= new_services_paper_url(@service) %>" class="btn btn-success btn-sm">New Paper Type</a></h5>
<% papers = @service.papers %>
<% if papers.present? %>
<table class="table table-hover">
    <tr>
      <td>#</td>
      <td>Size</td>
      <td>Type</td>
      <td>Colour</td>
      <td>Unit</td>
      <td>Price</td>
      <td>Options</td>
    </tr>
    <% cnt = 0 
      papers.order("created_at DESC").each do |paper| %>
    <tr>
      <td><%= cnt += 1%></td>
      <td><%= paper.size %></td>
      <td><%= paper.ptype %></td>
      <td><%= paper.color %></td>
      <td><%= paper.unit %></td>
      <td><%= "#{paper.currency}#{paper.price}" %></td>
      <td>
        <a href="<%= edit_services_paper_url(@service,pid: paper) %>" class="btn btn-primary btn-sm"> <%= fa_icon "pencil" %> Edit</a>
        <%= link_to('Delete', services_paper_url(@service, pid: paper), method: :delete, class: "btn btn-danger btn-sm") %>
      </td>
    </tr>
    <% end %>
</table>
<% else %>
    <center><h4>No Paper assigned to service.</h4></center>
<% end %>