config/routes.rb
# require 'resque/server'
Rails.application.routes.draw do
  devise_for :users, :path => ""


  # Of course, you need to substitute your application name here, a block
  # like this probably already exists.
  # mount Resque::Server.new, at: "/resque"
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  # Api for grape
  mount API => '/'

  resources :users, :path => "", only: :index do
  end

  resources :presses do
  	member do 
      put :toggle
      get :inventory
      get :metrics
  	end
  end

  resources :rannars do
    collection do
      get "delivery"
    end
    member do
    end
  end

  resources :orders do
    member do
      get :download
      post :status
    end
  end

  resources :countries
  resources :vouchers do
    collection do
      get   :print
      post  :get_pdf
    end
  end
  resources :customers
  
	resources :transactions do
		collection do
			get :export_csv
		end
	end
	resources :reports
	resources :settings do
		collection do
			put :password
		end
	end

  resources :dashboards
  resources :charges
  resources :services do
    member do
      namespace :services do
        resources :papers
      end
    end
  end

  root "dashboards#index"
end

app/controllers/settings_controller.rb
class SettingsController < UsersController

	# Index page of settings
	def index
		@user = current_user
	end

	# Update user profile settings
	def update
		@user = current_user
		if current_user.update_attributes(user_params)
			flash[:notice] = "Profile update successful."
		else
			flash[:alert] = "Profile update failed"
		end

		redirect_to settings_url
	end

	# changes password
	def password
		if current_user.valid_password?(params[:current_password])
			if current_user.update_attribute(:password, params[:password])
				flash[:notice] = "Password successfully changed."
			else
				flash[:alert] = "Error changing password. Please try again.#{current_user.errors.as_json}"
			end
		else
			flash[:alert] = "Current password is invalid."
		end

		redirect_to settings_url
	end

	private
	def user_params
		{first_name: params[:first_name],
		last_name: params[:last_name],
		email: params[:email]}
	end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/index.html.erb
<div class="container" style="padding-top: 50px">
	<div class="row justify-content-center">
		<div class="col-md-8">
			<h3>PROFILE SETTINGS</h3><br>
			<div class="alert alert-primary" role="alert">
			  Basic Profile Information
			</div>
			<%= form_tag setting_path(current_user), method: :put %>
				<div class="form-group row">
					<label for="first_name" class="col-md-3">First Name</label>
					<input type="text" class="form-control col-md-8" name="first_name" value="<%= @user.first_name %>" />
				</div>
				<div class="form-group row">
					<label for="last_name" class="col-md-3">Last Name</label>
					<input type="text" class="form-control col-md-8" name="last_name" value="<%= @user.last_name %>" />
				</div>
				<div class="form-group row">
					<label for="email" class="col-md-3">Email</label>
					<input type="email" class="form-control col-md-8" name="email" value="<%= @user.email %>" />
				</div>
				<div class="form-group row">
					<div class="col-md-3"></div>
					<input type="submit" value="Update Profile" class="btn btn-success btn-block col-md-8" />
				</div>
			</form>
			<br><br>
			<br><br>
			<div class="alert alert-primary" role="alert">
			  Password Settings
			</div>
			<%= form_tag password_settings_url, method: :put %>
				<div class="form-group row">
					<input type="hidden" name="user[email]" value="<%= current_user.email %>" />
					<label for="current_password" class="col-md-3">Current Password</label>
					<input type="password" class="form-control col-md-8" name="current_password" />
				</div>
				<div class="form-group row">
					<label for="new_password" class="col-md-3">New Password</label>
					<input type="password" class="form-control col-md-8" name="password" id="password" />
				</div>
				<div class="form-group row">
					<label for="confirm_password" class="col-md-3">Confirm Password</label>
					<input type="password" class="form-control col-md-8" name="password_confirmation" id="conf_password" />
				</div>
				<div class="form-group row">
					<div class="col-md-3"></div>
					<input type="submit" value="Change Password" class="btn btn-success btn-block col-md-8" />
				</div>
			</form>
		</div>
	</div>
</div>

<script type="text/javascript">
  var password = document.getElementById("password")
  , confirm_password = document.getElementById("conf_password");

  function validatePassword(){
    if(password.value != confirm_password.value) {
      confirm_password.setCustomValidity("Passwords Don't Match");
    } else {
      confirm_password.setCustomValidity('');
    }
  }

  password.onchange = validatePassword;
  confirm_password.onkeyup = validatePassword;
</script>