config/routes.rb
# require 'resque/server'
Rails.application.routes.draw do
  devise_for :users, :path => ""


  # Of course, you need to substitute your application name here, a block
  # like this probably already exists.
  # mount Resque::Server.new, at: "/resque"
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  # Api for grape
  mount API => '/'

  resources :users, :path => "", only: :index do
  end

  resources :presses do
  	member do 
      put :toggle
      get :inventory
      get :metrics
  	end
  end

  resources :rannars do
    collection do
      get "delivery"
    end
    member do
    end
  end

  resources :orders do
    member do
      get :download
      post :status
    end
  end

  resources :countries
  resources :vouchers do
    collection do
      get   :print
      post  :get_pdf
    end
  end
  resources :customers
  
	resources :transactions do
		collection do
			get :export_csv
		end
	end
	resources :reports
	resources :settings do
		collection do
			put :password
		end
	end

  resources :dashboards
  resources :charges
  resources :services do
    member do
      namespace :services do
        resources :papers
      end
    end
  end

  root "dashboards#index"
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_documents
  has_many :documents, through: :order_documents

  belongs_to :press
  belongs_to :customer

  has_many :order_extracharges, dependent: :destroy
  has_many :extra_charges, through: :order_extracharges

  # Country from which order comes from
  has_one :country

  # Order has many documents
  has_many :order_documents, dependent: :destroy
  has_many :documents, through: :order_documents, dependent: :destroy

  # Delivery information
  has_one :delivery, dependent: :destroy

  # Comments on order
  has_many :order_comments, dependent: :destroy
  has_many :comments, through: :order_comments

  # Collection logs
  # thus how the order is exchanged
  # MAX 2
  has_many :collection_logs, dependent: :destroy

  # Charges
  has_one :charge_log, dependent: :destroy

  # Money fields
  money_fields :amount, :copies_amount

  # Calculation of order
  def complete!(is_complete = true)
    self.update_attributes(is_complete: is_complete, is_viewed: true)
  end

  # State of order
  def order_complete!
    self.update_attributes(state: "complete", is_viewed: true)
  end

  # Provides the geolocation of document
  def get_geolocation
    case self.status
    when "pending_confirmation", "pending_pickup"
      {lat: "", lng: ""}
    when "in_delivery"
      {lat: "", lng: ""}
    when "complete", "cancelled"
      customer_gp = self.customer.gp
      {lat: customer_gp.lat, lng: customer_gp.lng}
    end
  end

  # Updates invoice amount
  def update_amount(params)
    self.update_attributes(amount: params[:grand_total],
                           is_estimated: true,
                           state: "pending_confirmation",
                           copies_amount: params[:copies_amount],
                           no_of_sheets: params[:no_of_sheets])
  end

  # Get any additional cost
  # of customer
  def additional_cost
    Money.new(self.extra_charges.sum(:amount_in_pesewas), self.currency)
  end

  # Get the extra charges in a string
  def string_extra_charges
    self.extra_charges.map { |charge| "#{charge.name.titleize}:  #{charge.currency}#{charge.amount.to_f}" }.join("\n")
  end

  # Builds delivery
  def delivery
    super || build_delivery.save ? super : build_delivery
  end

  # Reviewed order
  def reviewed!
    self.update_attributes(state: "reviewed")
  end

  # Reject order
  def rejected!(message = nil, from = "")
    self.update_attribute(state: "rejected", is_viewed: true)

    if message.present?
      comment = Comment.new(message: message, from: from)
      if comment.save
        self.comments << comment
      end
    end
  end

  # Check whether order is rejected
  def rejected?
    self.state == "rejected"
  end

  def confirmed?
    self.state == "confirmed"
  end

  def pending?
    self.state == "pending_confirmation"
  end

  # Archives an order
  def archive!(user, reverse = false)
    update_params = {}

    # Get current flags and split
    current_flags = self.archive_flags.split(",")
    flag = reverse ? "0" : "1"

    case user
    when "customer"
      current_flags[0] = flag
    when "press"
      current_flags[1] = flag
    when "runner"
      current_flags[2] = flag
    end

    # If is archived by customer
    # then the whole order is being removed
    # order can only be archived by customer
    # if it is not confirmed or it is completed
    update_params.merge!({archive_flags: current_flags.join(",")})
    if user == "customer"
      flag = !reverse
      update_params.merge!({is_archived: flag})
    end

    # Update the archive state
    self.update_attributes(update_params)
  end

  # checks whether an order has been
  # deleted
  def archived?(user, reverse = true)
    # Get current flags and split
    current_flags = self.archive_flags.split(",")
    flag = reverse ? "1" : "0"

    case user
    when "customer"
      return current_flags[0] == flag
    when "press"
      return current_flags[1] == flag
    when "runner"
      return current_flags[2] == flag
    else
      return true
    end
  end

  # Unarchive transaction
  def unarchive!(user)
    archive!(user, true)
  end

  # Unarchive transaction
  def confirmed!
    self.update_attributes(state: "confirmed", is_invoice: false)
  end

  # Unarchive transaction
  def delivered!
    self.update_attributes(state: "delivered")
  end

  # Amount minus the fees
  def amount_without_fees
    self.amount - self.extra_charges.find_by_name("print_fees").amount
  end
end

app/controllers/orders_controller.rb
class OrdersController < UsersController
  before_action :build_query, only: [:index]
  before_action :load_order, only: [:download, :show, :status]

  # Provide list of orders
  # according to search filter provided
  def index
    @orders = Order.where(@query)
      .order("created_at DESC")
      .page(params[:page] || 1)
  end

  # Shows the details of a transaction
  # Allow support team to help with transaction
  # issues
  def show
  end

  # Downloads the files of the order
  # onto the machine
  def download
    bucket = $amazon_s3.bucket("peipadbapp")

    files = @order.documents.pluck(:file_url)

    # Open the zip stream
    require "zip"
    zip_stream = Zip::OutputStream.write_buffer do |zip|

      # Loop through the files we want to zip
      files.each do |file_name|

        # Get the file object
        file_obj = bucket.object("#{file_name}")

        # Give a name to the file and start a new entry
        zip.put_next_entry(file_name.split("/").last)

        # Write the file data to zip
        begin
          zip.print file_obj.get.body.read
        rescue => exception
          flash[:error] = "Please check your internet connection."
          redirect_to orders_path(view_status: params[:view_status])
          return
        end
      end
    end

    # Rewind the IO stream so we can read it
    zip_stream.rewind

    # Create a temp file for the zip
    tempZip = Tempfile.new([@order.uid, ".zip"])

    # Write the stringIO data
    tempZip.binmode
    tempZip.write zip_stream.read

    send_file tempZip
    # Send it to s3
    # zip_file.upload_file(tempZip)
    # Clean up the tmp file
    # tempZip.close
    # tempZip.unlink
  end

  # Change the status of an order
  def status
    customer = @order.customer
    params[:country] = customer.country.name
    params[:msisdn] = @order.press.msisdn
    params[:order_uid] = @order.uid

    # Process the order and get the status
    result = PeipaPress::OrderLib::Engine.process(service: "status",
                                                  params: params)

    if result[:success]
      flash[:notice] = result[:message]
    else
      flash[:error] = result[:message]
    end

    redirect_to orders_path(view_status: params[:view_status])
  end

  def load_order
    @order = Order.find(params[:id])
    unless @order.present?
      flash[:error] = "Order not found"
      redirect_to orders_path(view_status: params[:view_status])
      return
    end
  end

  private

  def build_query
    @query = []
    if params[:q].present?
      @query += ["uid LIKE '\%#{params[:q].upcase}\%'"]
    end

    if params[:from].present?
      @query += ["created_at >= '#{params[:from].strip.to_time}'"]
    end

    if params[:to].present?
      @query += ["created_at <= '#{params[:to].strip.to_time}'"]
    end

    if params[:cid].present?
      @query += ["customer_id = '#{params[:cid]}'"]
    end

    if current_user.press.present?
      @query += ["press_id = '#{current_user.press.id}'"]
    end

    # Viewing status of the order
    if params[:v_stat].present?
      case params[:v_stat]
      when "new"
        @query += ["is_viewed = false"]
      when "viewed"
        @query += ["is_viewed = true"]
      else
      end
    end

    # Pull all unarchived transactions
    @query += ["is_archived = false"]

    @query = @query.join(" AND ")
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def color_format(color)
    if color.downcase.include? "col"
      "<span class='badge badge-danger'>#{color}</span>".html_safe
    else
      color
    end
  end
end

app/views/orders/partials/_order_list.html.erb
<% 	@orders.where(is_viewed: is_viewed).each do |order| %>
  <tr>
    <td>
      <% unless order.is_viewed? %>
        <span class="badge badge-success">NEW</span>
      <% end %>
    </td>
    <td><a href="<%= order_path(order) %>"><%= order.uid %></a></td>
    <td><a href="<%= customer_path(order.customer) %>"><%= order.customer.full_name %><br>
      <%= order.customer.msisdn %></a></td>
    <% order_specs = order.specs %>
    <td><%= order_specs["service_type"] %></td>
    <td><%= order.no_of_sheets %></td>
    <td><%= "#{order.amount.currency.code}#{order.amount.to_f}" %></td>
    <td>
      <b>Paper Type: </b> <%= order_specs["paper_type"]["ptype"] %><br>
      <b>Paper Size: </b> <%= order_specs["paper_type"]["size"] %><br>
      <b>Print Colour: </b> <%= color_format(order_specs["paper_type"]["color"]) %>
    </td>
    <td>
      <% if order_specs["make_copies"]
        copy_specs = order_specs["copy_paper_type"] %>
        <b>Make Copies: </b> YES <br>
        <b>Number of Copies: </b> <%= order_specs["no_of_copies"] %><br>
        <b>Paper Type: </b> <%= copy_specs["ptype"] %><br>
        <b>Paper Size: </b> <%= copy_specs["size"] %><br>
        <b>Print Colour: </b> <%= color_format(copy_specs["color"]) %>
      <% else %>
        <b>Make Copies: </b> NO <br>
      <% end %>
    </td>
    <td><%= order.state.titleize %></td>
    <td><center><%= order.delivery.location.present? ? "<span class='badge badge-success'>Yes</span>".html_safe : "<span class='badge badge-danger'>No</span>".html_safe %></center></td>
    <td><%= order.created_at.strftime("%d-%m-%Y %H:%M:%S") %></td>
    <td>
      <% if order.confirmed? %>
        <%= link_to '<i class="fa fa-check btn btn-success"></i>'.html_safe, status_order_path(id: order, state: 'complete',view_status: params[:view_status]), title: "Complete Order", class: 'show_loader', method: :post %>
        <%= link_to '<i class="fa fa-times btn btn-warning"></i>'.html_safe, status_order_path(id: order, state: 'rejected',view_status: params[:view_status]), title: "Reject Order", class: 'show_loader', method: :post %>
      <% end %>
      <% if order.pending? %>
        <%= link_to '<i class="fa fa-times btn btn-warning"></i>'.html_safe, status_order_path(id: order, state: 'rejected',view_status: params[:view_status]), title: "Reject Order", class: 'show_loader', method: :post %>
      <% end %>
      <a title="Download order" href="<%= download_order_path(order) %>"><i class="fa fa-download btn btn-success"></i></a>
    </td>
  </tr>
<% end %>